name = "Deconvolution"
uuid = "41ba435c-a500-5816-a783-a9707c6f5f3a"
authors = ["Mos√® Giordano <mose@gnu.org>"]
version = "0.3.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"

[compat]
FFTW = "0.0, 0.1, 0.2, 0.3, 1"
julia = "1"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random"]
